### ISSUE TITLE
how to read user data

### ISSUE THREAD

**Issue by Jack85** [dgrubelic/vue-authenticate#15]
letsay I have provider like this.. 
```
 google: {
      clientId: 'SOMENUMBER.apps.googleusercontent.com',
      redirectUri: 'http://localhost:8080/auth/callback' // Your client app URL
    }
```
and method like this..
```
	 authenticate(provider) {
		 this.$auth.logout();
            this.response = null
			this.$auth.authenticate(provider).then(function (authResponse) {
				console.log('authcalled');
				// Execute application logic after successful social authentication
			})
	   }
```
but after login I select google account it want to go 
/auth/google 
no matter what i do, how do pick user data response in js client. 
Do I really need server part at client app?
and how to read user data?

**Comment by dgrubelic** [comment]
In provided example in vue-authenticate lib source, i send response from Google access_token request directly to client after `/auth/google` request so you can collect that data directly from `authResponse` in `authenticate()` method (like you have in your example). Try to do `console.log(authResponse)` in your example and you'll see response from Google server returning access_token.

And yes, you need server part because of security. You need get access_token, and for that you need client secret. Exposing that to client app is big security risk.

**Comment by Jack85** [comment]
I probably dont get it. I dont understand why you have to go twice to google, first time from client app with client secret and secondtime from client server?
Although I saw your example its not clear to me. 
Could you describe most simplistic scenario for client app?
What I see I have to implement client app with auth request via 
`auth('google')`
and then on my server implement /auth/google 
response and then again read it with client?

**Comment by dgrubelic** [comment]
You are not sending client secret in the first request (from popup) where you do Google authentication but client id (your google app id). After this request you get request code (code param). After that `/auth/google` request is made to your server with code parameter from where you send another request to Google with code and client id & secret (secret you must be kept secret for security reasons). This is just how OAuth2 flow is created.

You find more info here (since vue-authenticate is heavily inspired by Satellizer and the flow is the same): https://github.com/sahat/satellizer#-login-with-oauth-20

**Comment by Jack85** [comment]
Thanks.

**Comment by Jack85** [comment]
Just one question, hot do I change that /auth/google url lets say I ll host it on port or different url?

**Comment by dgrubelic** [comment]
To change only relative path, you can do something like this:
```javascript
Vue.use(VueAuthenticate, {
  providers: {
    google: {
      url: '/custom-path/auth/google'
    }
  }
})
```

To host your api on different domain, you change `baseUrl` property:

```javascript
Vue.use(VueAuthenticate, {
  baseUrl: 'https://my-custom-domain.com',
})
```

https://github.com/dgrubelic/vue-authenticate/blob/master/src/options.js#L5

You can find full configuration object here https://github.com/dgrubelic/vue-authenticate/blob/master/src/options.js#L36, the same object format you can pass to `VueAuthenticate` plugin.

in the end, request will be sent to `https://my-custom-domain.com/custom-path/auth/google`.

**Comment by Jack85** [comment]
Cool stuff, thanks!
Hope to see how you tune this project further.
