### ISSUE TITLE
app.js:17551 Uncaught TypeError: _vueAuthenticate2.default.factory is not a function

### ISSUE THREAD

**Issue by arysom** [dgrubelic/vue-authenticate#8]
It is me again :)

When making new instance of Vue Authenticate, no matter in app.js or store.js it gives me error. My code:

```
const vueAuth = VueAuthenticate.factory(Vue.http, {
  baseUrl: 'http://localhost:4000'
})
```

**Comment by dgrubelic** [comment]
How did you include VueAuthenticate?

**Comment by arysom** [comment]
import VueAuthenticate from 'vue-authenticate'

I'm doing it inside store.js

**Comment by dgrubelic** [comment]
Yes, i thought so... For ES6 (i have to cover that case in README.md) you can still use:

```javascript
import { VueAuthenticate } from 'vue-authenticate'

const authInstance = new VueAuthenticate($http, {
  // options
})
```

since your your code is actually importing module file, which is `dist/vue-authenticate.es2015.js` file which has `export { VueAuthenticate }` at the end of the file https://github.com/dgrubelic/vue-authenticate/blob/master/dist/vue-authenticate.es2015.js#L1270

For all other use cases (ES5, CommonJS) you need to use `VueAuthenticate.factory($http, options)` to create instance.

**Comment by arysom** [comment]
hmm now I have `Uncaught TypeError: Cannot read property 'interceptors' of undefined`

**Comment by dgrubelic** [comment]
Can you gist your code?

Also, you can find working example here: 

Repo: https://github.com/dgrubelic/vue-authenticate-site
Auth service: https://github.com/dgrubelic/vue-authenticate-site/blob/master/src/services/auth.js
Store auth module: https://github.com/dgrubelic/vue-authenticate-site/blob/master/src/store/auth.js

**Comment by dgrubelic** [comment]
Current version is v1.2.3 so please update and let me know if issue still persists.

**Comment by arysom** [comment]
I'll be inspecting in the morning,for sure, and I'll let you know. Best regards.

**Comment by arysom** [comment]
Now it's ok 👍  I had to pass whole object to VueAuthenticate, earlier it was Vue.$http, I put my files on [gist](https://gist.github.com/arysom/ab6aa5fba3126c78b7c6929bec79ea2b) for reference. Thank you!

**Comment by dgrubelic** [comment]
Great, i'm glad you resolved it and that everything works as it should. Closing issue...
